"""
variables Names are here as a dictionary so they can be imported and used in other scripts
"""

variable_names =  {
    'ACS':'Central Air-conditioning',
    'AGER':'Age-Restricted',
    'ASSOC':'Community Association',
    'BASE':'Foundation',
    'CAT':'Category Code',
    'CLOS':'Closing Costs in Sales Price',
    'CON':'Condominium',
    'DECK':'Deck',
    'DET':'Design of House',
    'DIV':'Division',
    'FINC':'Type of Financing',
    'FNBS':'Finished Basement',
    'FOYER':'Two-Story Foyer',
    'FRAME':'Framing Material',
    'GAR':'Parking Facility',
    'HEAT':'Primary Space Heating System',
    'HEAT2':'Second Space Heating System',
    'LNDR':'Laundry Location',
    'METRO':'Metropolitan Area',
    'MFGS':'Construction Method',
    'PATI':'Patio',
    'PRCH':'Porch',
    'SEWER':'Sewage Disposal System',
    'STOR':'Stories',
    'WAL1':'Primary Exterior Wall Material',
    'WAL2':'Secondary Exterior Wall Material',
    'WALS':'Secondary Exterior Wall Material',
    'WATER':'Water Supply Source',
    'AREA':'Square Foot Area of the Lot',
    'BEDR':'Bedrooms',
    'COMP':'Completion Date',
    'FNSQ':'Square Foot Area of Finished Basement',
    'FFNSQ':'Final Square Foot Area of Finished Basement at Completion',
    'FPLS':'Fireplace',
    'FULB':'Full Bathrooms',
    'HAFB':'Half Bathrooms',
    'LOTV':'Lot Value',
    'PVALU':'Permit value',
    'SALE':'Sale Date',
    'FSQFS':'Final Square Foot Area of House at Completion',
    'STRT':'Start Date',
    'CONPR':'Contract Price',
    'SLPR':'Sales Price',
    'SQFS':'Square Foot Area of House',
    'WEIGHT':'Weight',
    'FUEL':'Primary Space Heating Fuel',
    'FUEL2':'Second Space Heating Fuel',
    'FCONPR':'Final Contract Price at Completion',
    'FSLPR':'Final Sales Price at Completion',
    'AREA_F':'Square Foot Area of the Lot Flag',
    'FNSQ_F':'Square Foot Area of Finished Basement Flag',
    'FFNSQ_F':'Final Square Foot Area of Finished Basement at Completion Flag',
    'SLPR_F':'Sales Price Flag',
    'FSLPR_F':'Final Sales Price Flag',
    'CONPR_F':'Contract Price Flag',
    'FCONPR_F':'Final Contract Price Flag',
    'LOTV_F':'Lot Value Flag',
    'SQFS_F':'Square Foot Area of House Flag',
    'FSQFS_F':'Final Square Foot Area of House at Completion Flag',
    'PVALU_F':'Permit Value Flag',
    'AUTH':'Permit Authorization Date',
}